___

TOPIC MODELLING
___

# Latent Dirichlet Allocation

## Data

We will be using articles from NPR (National Public Radio), obtained from their website [www.npr.org](http://www.npr.org)

In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/nluninja/text-mining-dataviz-aa2526/refs/heads/main/06-Topic_Modeling/npr.csv'

In [3]:
npr = pd.read_csv(url)

In [4]:
npr.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

Notice how we don't have the topic of the articles! Let's use LDA to attempt to figure out clusters of the articles.

In [5]:
npr.shape

(11992, 1)

## Preprocessing

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

**`max_df`**` : float in range [0.0, 1.0] or int, default=1.0`<br>
When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

**`min_df`**` : float in range [0.0, 1.0] or int, default=1`<br>
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

In [7]:
cv = CountVectorizer(max_df=0.95, min_df=0.2, stop_words='english')

In [8]:
dtm = cv.fit_transform(npr['Article'])

In [9]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 349867 stored elements and shape (11992, 96)>

## LDA

In [10]:
from sklearn.decomposition import LatentDirichletAllocation

In [11]:
LDA = LatentDirichletAllocation(n_components=7,max_iter=50,random_state=42)

In [12]:
# This can take awhile, we're dealing with a large amount of documents!
LDA.fit(dtm)

LatentDirichletAllocation(max_iter=50, n_components=7, random_state=42)

## Showing Stored Words

In [13]:
len(cv.get_feature_names_out())

96

### Showing Top Words Per Topic

In [14]:
len(LDA.components_)

7

In [15]:
LDA.components_

array([[3.10749994e+01, 2.39317109e+01, 1.97880251e+02, 1.43454304e-01,
        1.48235707e+01, 1.43453426e-01, 2.32973529e+01, 1.08155998e+01,
        1.08457060e+02, 1.43444876e-01, 1.65515728e-01, 4.61383446e+02,
        1.47961332e+02, 6.41312208e+01, 1.31140436e+02, 2.36680691e+02,
        4.92299621e+01, 1.72581410e+01, 7.56883598e+01, 1.43440238e-01,
        3.06075894e+01, 2.28623091e+02, 1.87607058e+02, 2.91707756e+01,
        2.91282710e+01, 6.27384533e+01, 1.02736004e+02, 1.43426251e-01,
        2.02952192e+02, 1.83116491e+02, 9.39690940e+00, 1.43488259e-01,
        2.47931760e+02, 1.32774327e+01, 9.69986529e+01, 3.14208384e+02,
        2.51850718e+02, 7.91366581e+01, 2.29182824e+02, 1.43452801e-01,
        1.43409202e-01, 1.33923932e+00, 1.43291573e-01, 5.04846133e+01,
        5.95641336e+01, 8.29494406e+00, 5.35147971e+01, 5.25511098e+01,
        3.41941966e+01, 2.80753136e+02, 1.17014777e+02, 5.43726034e+02,
        1.80027762e+02, 1.38376735e+03, 1.43385915e-01, 1.27413935e+02,
        9.29841260e+01, 3.50610098e+00, 6.69673190e-01, 8.30228380e+01,
        1.98761675e+01, 2.07403734e+02, 6.87229742e+02, 1.43359690e-01,
        1.82322574e+02, 1.45403782e-01, 7.50068533e+01, 3.37926768e+01,
        1.43376287e-01, 1.00811408e+04, 4.08189934e+03, 1.43415028e-01,
        1.43394084e-01, 2.87858001e+01, 2.10066387e+00, 9.81392382e+01,
        1.43387028e-01, 7.73572594e+01, 1.43379164e-01, 1.43392983e-01,
        1.43157297e-01, 1.38680391e+01, 2.78330480e+01, 2.33549977e+02,
        3.21765224e+01, 1.34765000e+01, 4.10560914e+00, 1.21019744e+02,
        2.46157447e+02, 1.43445479e-01, 1.43393707e-01, 1.43419993e-01,
        1.22619125e+00, 1.43255145e-01, 4.86199074e+02, 9.11419431e+01],
       [3.32160600e+03, 1.46176349e+03, 2.28377501e+03, 2.80570474e+02,
        5.31033356e+02, 2.53784087e+03, 9.54191737e+01, 8.91464850e+02,
        8.50170796e+02, 4.39972014e+02, 1.69727717e+02, 2.75206418e+01,
        1.87904997e+03, 3.80163919e+02, 4.84542790e+02, 2.87864941e+03,
        2.77532436e+02, 1.27161735e+02, 1.56122530e+02, 4.45156165e+00,
        5.05242157e+02, 3.78818536e+02, 2.79615099e+02, 4.59299697e+01,
        2.69279837e+02, 4.94542923e+02, 7.00478396e+02, 4.67754031e+02,
        9.88742797e+02, 3.30054323e+01, 5.24642401e+02, 3.40462303e+01,
        1.14439903e+03, 1.38561548e+03, 8.90816544e+02, 2.73636149e+02,
        1.43366345e-01, 1.22543491e+03, 1.00647264e+03, 1.43392944e-01,
        1.43398748e-01, 9.23834392e+00, 1.43353208e-01, 5.86390706e+02,
        1.69587080e+02, 6.20663016e+01, 5.34650348e+02, 3.43832129e+02,
        1.74590343e+02, 1.26856747e+03, 5.13349781e+02, 1.77676770e+03,
        1.03148482e+03, 4.19327139e+03, 3.31877153e+02, 3.22111377e+02,
        1.03197106e+03, 5.76788926e+03, 8.02061409e+03, 4.82391523e+02,
        4.47396480e+02, 8.01300991e+02, 1.85796492e+03, 1.43383075e-01,
        2.03529831e+02, 1.43401594e-01, 6.92770493e+02, 2.65038184e+01,
        1.43400667e-01, 1.43200582e-01, 1.12208320e+03, 1.43437256e-01,
        1.43429838e-01, 3.03178903e+01, 1.43467884e-01, 9.21879888e+02,
        6.22420071e+02, 8.19185154e+02, 1.43433465e-01, 7.52536939e+01,
        1.43082226e-01, 1.43450929e-01, 1.52127448e+03, 6.88803128e+02,
        6.04726756e+02, 4.17194962e+02, 1.45733900e+01, 6.14240882e+02,
        6.62718328e+02, 3.42747459e+01, 2.91074486e+02, 9.69365440e+02,
        4.71271393e+02, 2.89055266e+03, 5.27111982e+03, 2.75620481e+03],
       [1.43351817e-01, 1.40687220e+02, 1.43301792e-01, 2.11371807e+03,
        1.42704225e+02, 2.68137583e+02, 7.96080376e+02, 1.85882524e+03,
        1.66814193e+03, 7.07424966e+02, 6.18379250e+02, 3.11588089e+02,
        1.07148492e+03, 1.76870500e+03, 8.90538895e+02, 4.57629174e+02,
        4.71218169e+02, 1.00266682e+02, 2.15630815e+03, 2.34272070e+03,
        2.55974198e+03, 1.66717212e+03, 2.04071814e+03, 2.19672121e+03,
        6.94017349e+03, 6.85747792e+02, 1.30355400e+03, 2.71330263e+01,
        3.89083976e+02, 5.89055369e+03, 3.00088567e+03, 2.34109431e+03,
        1.43319436e-01, 2.23224043e+02, 1.13619596e+03, 9.30768552e+01,
        1.95970206e+01, 4.76215951e+01, 8.74043849e+03, 3.12519105e+03,
        7.19241248e+03, 5.83499248e+01, 1.28659176e+03, 1.09379930e+04,
        1.64722943e+03, 1.75854903e+03, 8.60636116e+02, 2.30329686e+03,
        4.44948286e+03, 4.17108879e+03, 1.26172213e+03, 3.67744934e+00,
        2.49994452e+03, 1.49328277e+03, 1.67569604e+02, 7.66204958e+02,
        2.92048804e+02, 1.16130198e+04, 1.43245625e-01, 7.73252604e+02,
        1.54504955e+03, 1.43320035e-01, 3.00508769e+02, 6.43819842e+03,
        2.92960933e+03, 3.88341927e+02, 3.67154294e+03, 8.66613938e+02,
        4.16914825e+01, 1.43143866e-01, 1.43333287e-01, 9.36298692e+02,
        3.07074087e+03, 4.41180522e+03, 8.93815477e+03, 3.42890092e+03,
        4.21719553e+02, 4.24271061e+02, 6.65557651e+01, 2.68521965e+02,
        1.43038016e-01, 1.49051052e+03, 4.73501393e+02, 1.20019445e+03,
        7.25244097e+02, 4.72646983e+03, 4.22651795e+03, 5.16316687e+03,
        4.45480902e+02, 6.10144793e+02, 2.72367234e+02, 2.42482280e+03,
        9.86135822e+02, 1.52638164e+03, 2.10202320e+02, 8.92645465e+02],
       [9.23231443e+02, 5.85650904e+02, 2.94685837e+03, 7.20934135e+01,
        3.13368064e+02, 5.00369127e+02, 4.63431877e+02, 1.43417919e-01,
        1.43381333e-01, 1.50955980e+03, 5.84806910e+02, 2.17514274e+03,
        1.42692495e+02, 2.55028886e+02, 2.25558845e+02, 1.36181604e+03,
        6.40281431e+02, 8.28328919e+02, 1.69239459e+03, 5.41077402e+02,
        1.50646539e+02, 2.70561493e+02, 1.24100793e+02, 1.77057310e+02,
        4.14659893e+02, 5.38366412e+02, 2.00699869e+02, 6.05406503e+02,
        3.36717563e+02, 4.48225565e+02, 3.95191480e+01, 4.56655394e+00,
        3.37635763e+03, 1.59827775e+03, 7.71014302e+02, 2.70484157e+02,
        1.84750540e+02, 1.44157355e+03, 4.56401594e+02, 2.59863717e+01,
        2.29373014e+02, 9.80414931e+02, 1.43386027e-01, 9.21093496e+00,
        6.46357277e+00, 1.15728897e+02, 3.31250874e+02, 2.27820754e+01,
        1.43452634e-01, 2.94754472e+02, 2.13152609e+02, 1.43494798e+03,
        3.51139972e+02, 1.00172649e+03, 3.32759182e+03, 3.83900144e+03,
        3.47571262e+02, 4.69795891e+03, 1.43169051e-01, 5.35422269e+02,
        3.18100202e+02, 1.93220260e+03, 1.85017870e+03, 1.43340447e-01,
        4.41527801e+02, 2.23823596e+04, 2.19457216e+03, 1.30382514e+03,
        9.85408302e+02, 1.43254160e-01, 1.43460198e-01, 4.35708659e+02,
        1.43453476e-01, 1.01440258e+02, 2.10732153e-01, 1.75430912e+03,
        1.03666390e+03, 4.96877573e+02, 4.43543653e+03, 9.31567832e+02,
        1.43080626e-01, 3.67118338e+02, 3.42097881e+02, 9.99376667e+02,
        1.23228313e+03, 1.24221497e+02, 4.67142016e+02, 1.94776425e+02,
        1.43567589e+03, 4.60587810e+02, 2.71189963e+00, 5.54259962e+02,
        3.99557955e+02, 1.80252348e+01, 7.39587754e+02, 1.13601515e+03],
       [1.18565744e+03, 4.24757237e+02, 5.58144747e+02, 6.94241014e+02,
        9.48388458e+02, 5.04406688e+01, 6.90039262e+02, 5.36105337e+02,
        7.80221740e+02, 1.20614204e+03, 3.59070398e+02, 6.30113226e+02,
        6.05650333e+02, 1.08960447e+03, 4.02575878e+02, 7.00952971e+02,
        8.72885655e+02, 5.69152405e+02, 2.00106322e+02, 5.80302401e+02,
        6.51310192e+02, 4.00180222e+02, 1.09172316e+03, 5.92733476e+02,
        2.38787699e+03, 3.69083842e+02, 9.51839164e+01, 5.34510813e+02,
        6.09829458e+02, 1.60546394e+03, 7.97400412e+02, 6.36425608e+02,
        1.09862985e+03, 1.28064940e+03, 2.00611699e+03, 8.15539246e+02,
        8.19210343e+01, 6.95098005e+02, 3.02657430e+03, 5.02748909e+02,
        1.09395378e+03, 2.59541505e+02, 2.37978383e+01, 3.74473443e+03,
        6.58525123e+02, 5.87731546e+02, 7.41106249e+02, 4.27385850e+02,
        1.42914026e+03, 1.54493166e+03, 4.05596713e+02, 7.16831411e+02,
        1.23544981e+03, 1.79283525e+03, 2.09413106e+02, 2.00674522e+01,
        4.24766168e+02, 6.05384658e+03, 1.43400143e-01, 5.78637581e+02,
        1.53405492e+02, 1.57613657e+01, 7.99189658e+02, 1.46170576e+03,
        8.78304438e+02, 1.43335336e-01, 2.02557772e+03, 1.40368482e+02,
        4.49412432e+04, 1.43176041e-01, 1.43350989e-01, 8.32786455e+01,
        2.71113541e+02, 5.08742226e+02, 1.06308685e+03, 1.31267801e+03,
        2.18196502e+02, 3.20285127e+02, 1.11790730e+02, 4.34116399e+02,
        1.42980682e-01, 9.10738875e+02, 2.26249984e+03, 1.77609933e+03,
        1.54424401e+03, 9.20335117e+02, 1.42227975e+03, 1.04642380e+03,
        3.15502786e+02, 1.97794504e+02, 1.43440645e-01, 1.74016541e+03,
        9.43170974e+02, 2.32168577e+02, 8.66402224e+02, 2.44566972e+03],
       [1.43459218e-01, 6.22742982e+02, 1.43438898e-01, 3.03036500e+02,
        1.49810773e+03, 1.61258351e+03, 1.48835575e+03, 5.64943910e+02,
        1.19967956e+03, 1.64172691e+03, 2.19495712e+03, 5.10097804e+02,
        6.10096788e+00, 1.49594618e+03, 7.83765141e+02, 8.35549548e+02,
        4.40885670e+03, 1.78108581e+03, 2.25271364e+03, 1.97182068e+03,
        8.25580927e+02, 6.67991759e+02, 3.84504611e+02, 2.85830925e+02,
        3.18156407e+02, 1.40460081e+03, 5.94910123e+02, 4.14888694e+03,
        7.46462358e+02, 4.36142833e+02, 1.17699352e+03, 2.05695220e+03,
        1.43284210e-01, 4.01850631e+02, 3.98939985e+02, 3.08491175e+03,
        1.59715535e+03, 7.73848219e+02, 4.66376011e+03, 8.56211921e+02,
        1.32677223e+03, 1.92204510e+03, 5.01603717e+03, 5.82409145e+03,
        2.12761029e+03, 1.10570135e+03, 2.17772116e+03, 7.99025365e+02,
        3.29269579e+02, 1.38441999e+03, 7.37502105e+02, 2.50369568e+01,
        3.10691006e+01, 6.17611681e+03, 1.62955833e+02, 8.99221518e+02,
        1.03871138e+03, 1.43349047e+02, 1.43140452e-01, 1.52363176e+03,
        8.77330021e+02, 1.43322532e-01, 8.52998960e+01, 4.31522389e+02,
        9.70660126e+02, 5.03088830e+02, 2.26169453e+02, 1.40172128e+02,
        2.26836795e-01, 1.43131814e-01, 1.43309005e-01, 3.17160826e+03,
        6.91457529e+02, 9.38682075e+02, 2.34300980e+02, 6.42621433e+03,
        1.58810118e+03, 1.36823676e+03, 1.62374372e+03, 1.56312891e+03,
        1.42966039e-01, 4.62461978e+02, 9.54139201e+01, 3.35634915e+01,
        5.18786220e+02, 1.06183434e+03, 3.94269168e+02, 2.61793888e+03,
        7.93733001e+02, 1.94003008e+03, 1.77498638e+03, 1.97849985e+03,
        5.40131116e+02, 3.67380660e+03, 2.53847610e+03, 5.61008159e+03],
       [1.43306184e-01, 4.34664605e+01, 1.00548747e+01, 1.90197072e+02,
        1.84574594e+02, 9.47484782e+02, 1.18376212e+02, 1.21701650e+02,
        3.71185525e+02, 6.11030824e+02, 3.22893093e+02, 4.31540502e+01,
        3.14059978e+02, 3.64420316e+02, 1.61878016e+02, 1.12872216e+03,
        4.67995642e+02, 4.52746313e+02, 9.95666412e+02, 3.25483816e+02,
        9.78706147e+01, 4.66652783e+02, 3.06731143e+02, 2.18556339e+02,
        3.44725116e+02, 1.83919767e+02, 3.38437688e+02, 6.81652628e+01,
        4.54211655e+02, 8.50492045e+02, 3.55161948e+02, 2.34771610e+02,
        6.10395136e+02, 8.01052633e+01, 1.40917564e+02, 1.43461483e-01,
        4.69158197e+03, 4.61287067e+02, 7.58170037e+02, 8.75748983e+01,
        2.69201690e+02, 4.58070958e+02, 1.43197931e-01, 2.75094864e+02,
        8.60203725e+01, 2.47927941e+02, 2.17120460e+02, 2.68126606e+02,
        5.51793121e+01, 5.10484488e+02, 2.10661884e+02, 1.25801247e+03,
        1.50884016e+02, 1.47399995e+03, 8.74449101e+02, 6.48979320e+02,
        3.58947192e+02, 1.75430248e+02, 1.43278377e-01, 1.32641420e+02,
        3.19842084e+02, 8.62504467e+03, 3.75628315e+02, 1.43343441e-01,
        3.48045903e+02, 5.59277747e+03, 6.26360390e+02, 8.04723820e+02,
        1.43355981e-01, 1.43251698e-01, 8.64444003e+02, 1.14818892e+02,
        1.11257779e+02, 2.00226527e+02, 6.00002540e+02, 5.48878505e+02,
        5.28755408e+02, 1.34787066e+02, 1.02918644e+03, 3.44267806e+02,
        2.28961417e+04, 1.98158802e+02, 4.73794410e+01, 7.44129566e+01,
        7.45392663e+01, 1.12467754e+02, 3.32112117e+02, 5.02433391e+02,
        1.21073164e+03, 2.44024623e+02, 4.24557316e+03, 1.98743124e+02,
        1.48506547e+02, 4.92203357e+00, 2.36012702e+02, 1.60241322e+02]])

In [16]:
len(LDA.components_[0])

96

In [17]:
single_topic = LDA.components_[0]

In [18]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([80, 93, 42, 63, 68, 78, 54, 76, 79, 90, 72, 40, 71, 91, 27, 19,  9,
       89, 39,  5,  3, 31, 65, 10, 58, 92, 41, 74, 57, 86, 45, 30,  7, 33,
       85, 81,  4, 17, 60,  6,  1, 82, 73, 24, 23, 20,  0, 84, 67, 48, 16,
       43, 47, 46, 44, 25, 13, 66, 18, 77, 37, 59, 95, 56, 34, 75, 26,  8,
       50, 87, 55, 14, 12, 52, 64, 29, 22,  2, 28, 61, 21, 38, 83, 15, 88,
       32, 36, 49, 35, 11, 94, 51, 62, 53, 70, 69])

In [19]:
# Word least representative of this topic
single_topic[80]

np.float64(0.143157297330522)

In [20]:
# Word most representative of this topic
single_topic[69]

np.float64(10081.140841839071)

In [21]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([36, 49, 35, 11, 94, 51, 62, 53, 70, 69])

In [22]:
top_word_indices = single_topic.argsort()[-10:]

In [23]:
for index in top_word_indices:
    print(cv.get_feature_names_out()[index])

house
make
home
case
year
national
public
new
states
state

These look like business articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [24]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['just', 'use', 'country', 'week', 'government', 'house', 'make', 'home', 'case', 'year', 'national', 'public', 'new', 'states', 'state']


THE TOP 15 WORDS FOR TOPIC #1
['10', 'university', 'national', 'public', 'change', 'according', 'american', 'years', 'country', 'world', '000', 'new', 'year', 'people', 'percent']


THE TOP 15 WORDS FOR TOPIC #2
['say', 'make', 'want', 'things', 'lot', 've', 'way', 'going', 'really', 'don', 'know', 'just', 'think', 'like', 'people']


THE TOP 15 WORDS FOR TOPIC #3
['called', 'group', 'did', 'time', 'public', 'president', 'case', 'say', 'according', 'news', 'government', 'npr', 'told', 'people', 'said']


THE TOP 15 WORDS FOR TOPIC #4
['used', 'make', 'going', 'work', 'use', 'new', 'help', 'say', 'university', 'don', 'years', 'just', 'like', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #5
['came', 'did', 'year', 'way', 'home', 'story', 'world', 'family', 'day', 'just', 'life', 'years', 'like', 'new', 'time']


THE TOP 15 WORDS FOR TOPIC #6
['going', 'states', 'news', 'american', 'did', 'told', 'country', 'week', 'national', 'new', 'white', 'house', 'said', 'president', 'trump']

### Attaching Discovered Topic Labels to Original Articles

In [25]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 349867 stored elements and shape (11992, 96)>

In [26]:
dtm.shape

(11992, 96)

In [27]:
len(npr)

11992

In [28]:
topic_results = LDA.transform(dtm)

In [29]:
topic_results.shape

(11992, 7)

In [30]:
topic_results[0]

array([0.00150734, 0.00151148, 0.00151227, 0.0015112 , 0.00150877,
       0.32758589, 0.66486306])

In [31]:
topic_results[0].round(2)

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.33, 0.66])

In [32]:
topic_results[0].argmax()

np.int64(6)

This means that our model thinks that the first article belongs to topic #7.

### Combining with Original Data

In [33]:
npr.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [34]:
topic_results.argmax(axis=1)

array([6, 6, 6, ..., 5, 2, 4])

In [35]:
npr['Topic'] = topic_results.argmax(axis=1)

In [36]:
npr.head(10)

                                             Article  Topic
0  In the Washington of 2016, even when the polic...      6
1    Donald Trump has used Twitter  —   his prefe...      6
2    Donald Trump is unabashedly praising Russian...      6
3  Updated at 2:50 p. m. ET, Russian President Vl...      6
4  From photography, illustration and video, to d...      1
5  I did not want to join yoga class. I hated tho...      2
6  With a   who has publicly supported the debunk...      1
7  I was standing by the airport exit, debating w...      5
8  If movies were trying to be more realistic, pe...      4
9  Eighteen years ago, on New Year’s Eve, David F...      5

## Visualizing LDA

**pyLDAvis** is designed to help users interpret the topics in a topic model that has been fit to a corpus of text data. The package extracts information from a fitted LDA topic model to inform an interactive web-based visualization.

it's a Python library for interactive topic model visualization, port of the fabulous R package by Carson Sievert and Kenny Shirley.

In [37]:
!pip install pyldavis

Collecting pyldavis
  Downloading pyLDAvis-3.4.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: numpy>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from pyldavis) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pyldavis) (1.16.3)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pyldavis) (2.2.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from pyldavis) (1.5.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from pyldavis) (3.1.6)
Requirement already satisfied: numexpr in /usr/local/lib/python3.12/dist-packages (from pyldavis) (2.14.1)
Collecting funcy (from pyldavis)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pyldavis) (1.6.1)
Collecting gensim (from pyldavis)
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pyldavis) (75.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->pyldavis) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->pyldavis) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->pyldavis) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->pyldavis) (3.6.0)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim->pyldavis) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->pyldavis) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->pyldavis) (1.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim->pyldavis) (2.1.1)
Downloading pyLDAvis-3.4.1-py3-none-any.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 26.8 MB/s eta 0:00:00
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 62.5 MB/s eta 0:00:00
Installing collected packages: funcy, gensim, pyldavis
Successfully installed funcy-2.0 gensim-4.4.0 pyldavis-3.4.1

pyLDAvis now also supports LDA application from scikit-learn, but also gensim, that is an alternative library for LDA

In [38]:
import pyLDAvis
import pyLDAvis.lda_model
pyLDAvis.enable_notebook()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [39]:
pyLDAvis.lda_model.prepare(LDA, dtm, cv)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
2     -0.173444 -0.071659       1        1  24.972587
5     -0.098807 -0.002706       2        1  17.994203
4     -0.134537 -0.101396       3        1  17.704325
3      0.015769  0.141748       4        1  13.247767
1      0.028567 -0.063550       5        1  11.526480
6      0.061627  0.234562       6        1  11.019215
0      0.300825 -0.137000       7        1   3.535423, topic_info=         Term          Freq         Total Category  logprob  loglift
68       says  45786.000000  45786.000000  Default  30.0000  30.0000
80      trump  23031.000000  23031.000000  Default  29.0000  29.0000
65       said  28814.000000  28814.000000  Default  28.0000  28.0000
69      state  10582.000000  10582.000000  Default  27.0000  27.0000
58    percent   8053.000000   8053.000000  Default  26.0000  26.0000
..        ...           ...           ...      ...      ...      ...
29      going    192.204536   9424.960818   Topic7  -4.8679  -0.5502
55        npr    133.737470   6613.931497   Topic7  -5.2306  -0.5587
61  president    217.697152  11639.094943   Topic7  -4.7434  -0.6367
38       just    240.557135  18832.669399   Topic7  -4.6435  -1.0181
87        way    127.025936  10234.790047   Topic7  -5.2821  -1.0468

[280 rows x 6 columns], token_table=      Topic      Freq   Term
term
0         3  0.215967    000
0         4  0.168238    000
0         5  0.609864    000
0         7  0.006035    000
1         1  0.042376     10
...     ...       ...    ...
95        3  0.186341  years
95        4  0.086592  years
95        5  0.211661  years
95        6  0.012316  years
95        7  0.007343  years

[593 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[3, 6, 5, 4, 2, 7, 1])

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

pyLDAvis reference paper: https://cran.r-project.org/web/packages/LDAvis/vignettes/details.pdf
relevance definition: https://nlp.stanford.edu/events/illvi2014/papers/sievert-illvi2014.pdf